### ISSUE TITLE
File extension changed to ".rm"

### ISSUE THREAD

**Issue by TheFrenchGhosty** [jkwill87/mnamer#59] opened 2020-02-23 04:15 UTC
Some files (around 1%) will have their extension changed to .rm without any reason.

**Comment by jkwill87** [comment] 2020-02-24 03:18
I've never observed this. Interesting. Can this be reproduced for a given filename?

**Comment by TheFrenchGhosty** [comment] 2020-02-24 06:55
No, it seems really random, no idea why.

**Comment by mitchellcouchman** [comment] 2020-04-24 10:58
I'm having this happen too, but renaming to ".torrent". Any logs or anything I can get for you?

![mnamer](https://user-images.githubusercontent.com/28520777/80205644-52173a80-866e-11ea-97cd-813853c4c518.PNG)

**Comment by javier-alba** [comment] 2020-05-03 23:31
> I'm having this happen too, but renaming to ".torrent". Any logs or anything I can get for you?
> 
> ![mnamer](https://user-images.githubusercontent.com/28520777/80205644-52173a80-866e-11ea-97cd-813853c4c518.PNG)

Looks like TORRENT is a keyword. As a workaround try a different folder.
 
![image](https://user-images.githubusercontent.com/5985391/80928774-e9ae1480-8d63-11ea-9818-8d3175db49e7.png)

**Comment by jkwill87** [comment] 2020-05-13 03:43
@mitchellcouchman @javier-alba I was not able to reproduce this bug. `torrent` does not have any special treatment with mnamer. I think that this bug is something attributable to the version of `guessit` installed on your system. Either way, v2.3.5 has [a simple fix](958faf3ff220aa2b406c2cd1ef3d066e07f33625) that hopefully should sort out the issue for you.

If you update to v2.3.5 (e.g. by running `pip3 install --upgrade mnamer`) please let me know if that works. Also if you could run `pip3 freeze | grep guessit` that might help me figure out why this was happening.

@TheFrenchGhosty I'm not sure if this problem is directly related but it should hopefully fix your problem as well :crossed_fingers:

**Comment by jkwill87** [comment] 2020-05-21 02:46
Closing for now. If this issue is still present after updating I'll be happy to investigate further.

**Closed as completed by jkwill87** 2020-05-21 02:46 UTC
Labels: bug

**Comment by TheFrenchGhosty** [comment] 2021-01-18 01:15
@jkwill87 

>@TheFrenchGhosty I'm not sure if this problem is directly related but it should hopefully fix your problem as well

I completely forgot to come back here, but indeed this issue hasn't been a thing since months.
