### ISSUE TITLE
tvdb supports multiple target languages. a parameter should help to request the right language

### ISSUE THREAD

**Issue by elschman** [jkwill87/mnamer#76] opened 2020-05-06 06:16 UTC
thetvdb.com supports multiple target languages for the tv series. This should be supported by a parameter to be set if en i not the right one.

e.g. --tvdb-lang

**Comment by jkwill87** [comment] 2020-05-06 06:46
Duplicate of #9. Language and subtitle support will be added in mnamer v3.

**Closed as completed by jkwill87** 2020-05-06 06:46 UTC
Labels: duplicate, request

**Comment by jkwill87** [comment] 2020-07-07 02:28
Language support added in [v2.4.1](https://github.com/jkwill87/mnamer/releases/tag/2.4.1) :tada:
